{
 "title": "by_station",
 "description": "Monitoring station by station",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {}
   },
   { "name": "source", "label": "netdata", "query": "netdata" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System gauges",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($source.$server.system.cpu.user, 'CPU_user : $server')"
    },
    {
     "target": "alias($source.$server.system.ram.used, 'RAM_used : $server')"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU use by user",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(sortBy(aliasByTags($source.$server.user.*.system, 3), 'current', true), '\\B(_[a-z]+|_[1-9]+)', '')"
    }
   ]
  },
  {
   "title": "Memory use by user",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(sortBy(aliasByTags($source.$server.user.*.mem, 3), 'current', true), '\\B(_[a-z]+|_[1-9]+)', '')"
    }
   ]
  },
  {
   "title": "CPU use by process",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByTags(sortBy($source.$server.app.*.system, 'current', true), 3), '\\B(_[a-z]+|_[1-9]+)', '')"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU_system",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "alias($source.$server.system.cpu.user, 'CPU_system')"
    }
   ]
  },
  {
   "title": "RAM_used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 17 },
   "targets": [
    {
     "target": "alias($source.$server.system.ram.used, 'RAM_used')"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 17 },
   "targets": [
    {
     "target": "aliasByTags($source.$server.net.*.*, 4)"
    }
   ]
  }
 ]
}